language: node_js
addons:
  sonarcloud:
    organization: "probakilla-github"
    token: "38f236df61e1df16351b42469b8f6ad48dde3004"
node_js:
  - 8
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm test
  - sonar-scanner